### ISSUE TITLE
script not working at system start up

### ISSUE THREAD

**Issue by AlexB030** [akabdog/scripts#2]
Hey there,

I am using your script on a Ubuntu 14.04 Server and everything works fine, when calling 

sudo service kibana4_init start

manually. But it does not perform desired action at boot time.
I placed your script in /etc/init.d/ and I also symlinked it into all my rcX.d directories (I used update-rc.d for this), but kibana is not starting up at boot time. I always have to trigger it manually afterwards.

Do you have any clue what might cause this?

I also tried on a Ubuntu 14.10 server with the same effect.

Thanks,
Alex

**Comment by panophobicPanda** [comment]
glad to hear it's almost working for you. sounds like you know what your doing but can you check your runlevel and show me what the the directory looks like? I think there might be a bug in my #INIT INFO part of my script...
$ runlevel
N 2
$ ls -al /etc/rc2.d | grep kibana

**Comment by panophobicPanda** [comment]
I've made a change to the script, can you test it for me? I don't have access to my QA environment at the moment...
update-rc.d -f kibana4_init -f
update-rc.d -f kibana -f
<install new version>
update-rc.d kibana4_init defaults

thanks!

**Comment by panophobicPanda** [comment]
oops, i mean this:
update-rc.d -f kibana4_init -f
update-rc.d -f kibana -f
update-rc.d -f kibana4 -f
---install new version, then---
update-rc.d kibana4_init defaults

**Comment by AlexB030** [comment]
Hey, thanks for your respsonse.

My runlevel is 2
calling:
"$ runlevel" returns
N 2
"$ ls -al /etc/rc2.d | grep kibana" returns
lrwxrwxrwx   1 root root   22 Mar  1 22:12 S95kibana4_init -> ../init.d/kibana4_init
(I guess, that is expected)

I removed all my symlinks via 
"update-rc.d -f kibana4_init remove"
(the other commands did not apply for me but executed them anyway)
then I installed your new script
"update-rc.d kibana4_init defaults"

but I have the same phenomenon. Kibana does not start at bootup.

I made a diff on the old and new scripts. is it intended, that only the following three lines changed?

# Provides: kibana4_init  
# Short-Description: Starts kibana4_init  
# Description: Starts kibana4_init using start-stop-daemon  

Thanks,
Alex

**Comment by panophobicPanda** [comment]
Interesting, I'm not sure what the problem is then.

Does it start okay using "/etc/init.d/kibana4_init start" ?

Can you do a reboot and check /var/log/syslog for anything kibana related?

Where did you unpack kibana? In my testing I used "/opt/kibana/bin/kibana" for the daemon.

Can you do "su -" and then try starting it...its possible something we need is missing from root's $PATH that I would need to add manually to the script...

It could also be a problem with the "# Required-Start:" line, maybe those aren't starting prior to kibana? If you list all the files in /etc/rc2.d, I can take a look.

thanks for the help,
brian

**Comment by AlexB030** [comment]
Hi Brian,
sorry for the late response. I will go through your recommendations one by one.

"/etc/init.d/kibana4_init start" works totally fine (when I start it via sudo), as regular user of course I do not have the privileges.

in my syslog there is actually nothing kibana related (cat /var/log/syslog | grep kibana returned nothing)

Yes, i placed kibana in /opt/ so that starting kibana through /opt/kibana/bin/kibana is totally fine

"su -" does not work for me, since my root account is deactivated. But opening a pseudo root-shell with "sudo -s" works and from there I can call without any problem. Should I activate my root-account?

My rc2.d looks like this:
lrwxrwxrwx 1 root root  16 Jan 26 08:11 S01apport -> ../init.d/apport
lrwxrwxrwx 1 root root  19 Jan 26 08:09 S01cgmanager -> ../init.d/cgmanager
lrwxrwxrwx 1 root root  19 Jan 26 08:11 S01dns-clean -> ../init.d/dns-clean
lrwxrwxrwx 1 root root  23 Jan 29 21:51 S01elasticsearch -> ../init.d/elasticsearch
lrwxrwxrwx 1 root root  18 Jan 26 08:10 S01pppd-dns -> ../init.d/pppd-dns
lrwxrwxrwx 1 root root  17 Jan 26 08:01 S01rsyslog -> ../init.d/rsyslog
lrwxrwxrwx 1 root root  15 Jan 26 08:09 S01uuidd -> ../init.d/uuidd
lrwxrwxrwx 1 root root  17 Jan 26 22:59 S02apache2 -> ../init.d/apache2
lrwxrwxrwx 1 root root  15 Jan 26 22:59 S03acpid -> ../init.d/acpid
lrwxrwxrwx 1 root root  13 Jan 26 22:59 S03atd -> ../init.d/atd
lrwxrwxrwx 1 root root  17 Jan 26 22:59 S03cgproxy -> ../init.d/cgproxy
lrwxrwxrwx 1 root root  14 Jan 26 22:59 S03cron -> ../init.d/cron
lrwxrwxrwx 1 root root  14 Jan 26 22:59 S03dbus -> ../init.d/dbus
lrwxrwxrwx 1 root root  20 Jan 26 22:59 S03irqbalance -> ../init.d/irqbalance
lrwxrwxrwx 1 root root  18 Jan 29 22:23 S03logstash -> ../init.d/logstash
lrwxrwxrwx 1 root root  22 Mär 10 10:29 S03logstash-web -> ../init.d/logstash-web
lrwxrwxrwx 1 root root  15 Jan 26 22:59 S03mdadm -> ../init.d/mdadm
lrwxrwxrwx 1 root root  15 Feb 10 23:14 S03mysql -> ../init.d/mysql
lrwxrwxrwx 1 root root  15 Jan 26 22:59 S03rsync -> ../init.d/rsync
lrwxrwxrwx 1 root root  23 Feb 20 23:22 S03smartmontools -> ../init.d/smartmontools
lrwxrwxrwx 1 root root  13 Jan 26 22:59 S03ssh -> ../init.d/ssh
lrwxrwxrwx 1 root root  18 Jan 26 22:59 S03thermald -> ../init.d/thermald
lrwxrwxrwx 1 root root  22 Jan 26 22:59 S04avahi-daemon -> ../init.d/avahi-daemon
lrwxrwxrwx 1 root root  15 Feb 10 23:15 S04exim4 -> ../init.d/exim4
lrwxrwxrwx 1 root root  18 Jan 26 22:59 S05netatalk -> ../init.d/netatalk
lrwxrwxrwx 1 root root  21 Jan 26 22:59 S06grub-common -> ../init.d/grub-common
lrwxrwxrwx 1 root root  22 Mär 11 10:43 S06kibana4_init -> ../init.d/kibana4_init
lrwxrwxrwx 1 root root  18 Jan 26 22:59 S06ondemand -> ../init.d/ondemand
lrwxrwxrwx 1 root root  18 Jan 26 22:59 S06rc.local -> ../init.d/rc.local

Thanks,
Alex

**Comment by panophobicPanda** [comment]
Thanks for the info, if you could try a couple things, that'd be great:
1. pull down the latest version, the order was wrong on some of the variables
2. see if activating the root account makes any difference
3. try "sudo start-stop-daemon --start --pidfile /var/run/kibana4.pid --make-pidfile --background --exec /opt/kibana/bin/kibana" and see if theres any error messages or if it starts fine.

That's weird that there's no log messages, do all your other services start fine?

thanks,
b

**Comment by joaquinvanschoren** [comment]
Same thing happens to me. I 'solved' it by adding a 5-minute sleep at the beginning of the script. 
It seems that the script fails silently when elasticsearch is not ready yet?

**Comment by panophobicPanda** [comment]
thanks, can you tell me which line u added it to? or submit a change (pull
request).

On Friday, June 19, 2015, Joaquin Vanschoren notifications@github.com
wrote:

> Same thing happens to me. I 'solved' it by adding a 5-minute sleep at the
> beginning of the script.
> It seems that the script fails silently when elasticsearch is not ready
> yet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akabdog/scripts/issues/2#issuecomment-113506026.

## 

sent from iphone

**Comment by joaquinvanschoren** [comment]
It's simply a 'sleep 300' on line 32. You could perhaps do a loop that checks whether elasticsearch is available earlier.

I created a local branch with the fix, but I have no rights in your repo to push it and do a pull request.

**Comment by panophobicPanda** [comment]
Thanks so much for all the feedback from everyone, I've added a loop to test if elasticsearch is listening before starting the service. Please let me know if it works for you!
