### ISSUE TITLE
erroneous grep?

### ISSUE THREAD

**Issue by ityesnyou** [akabdog/scripts#7]

**Comment by svanpoeck** [comment]
Hi,

I believe the statement `"grep -e "\"status\" : 200"` is erroneous.
`curl 'http://localhost:9200'` does not return a status indication on my elasticsearch 2.0 installation.
Here's what it actually returns:

```
$ curl 'localhost:9200'
{
  "name" : "Bombshell",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

So I changed the Elasticsearch UP check to `if (echo "$response" | grep "elasticsearch"); then` to get it working for me.

HTH,
Steven

**Comment by ghost** [comment]
A slight modification to Curl and Grep got it working for mw

response=$(curl -I "http://$ES_HOST:9200")

and change the grep to 
(echo "$response" | grep -e "200 OK")

**Comment by panophobicPanda** [comment]
Thanks folks. I did the change proposed by @abrarahmedbcg and did some basic testing, seems to work.

**Comment by svanpoeck** [comment]
Thanks!
Steven
