### ISSUE TITLE
The script doesn't start Kibana

### ISSUE THREAD

**Issue by zappeee** [akabdog/scripts#8]
I tried running the script but it doesn't start kibana, so I have to start it manually

I'm using Ubuntu Mate 15.10.

In syslog I can see \* Starting Kibana4 and then HTTP/1.1 200 OK then false and ...done.
So I assume it finds ElasticSearch but for some reason Kibana doesn't start.

Any idea what I can do?

**Comment by panophobicPanda** [comment]
Can you do me a favor and try changing 
USER=nobody to USER=root ?

Also, does kibana start fine when you run it via <kibana home>/bin/kibana ?

**Comment by zappeee** [comment]
When changing to root it works.

Yes, manually it works fine.

**Comment by panophobicPanda** [comment]
Can you change USER=nobody then run
chown -R nobody <kibana directory>

I've added a comment to the script to remind people to do this, I hope it works for you.

If that doesnt work, try running this and see what happens (you may need to change some variables):

sudo start-stop-daemon --start --user nobody -c nobody --pidfile /var/run/kibana4.pid --make-pidfile --background --exec /opt/kibana/bin/kibana

ps -ef | grep kibana

**Comment by zappeee** [comment]
chown worked fine, thanks

**Comment by zappeee** [comment]
Never mind, that didn't work either.

When running that last command nothing happens.

**Comment by zappeee** [comment]
Ignore my previous comments :)

chown the folder worked great.
Why wasn't that needed before?
